server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/inventorydb}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  jwt:
    secret: ${JWT_SECRET:change-me-please-32-bytes-min}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
    issuer: inventory-app

logging:
  level:
    root: INFO
    org.springframework.security: INFO

